/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/issues/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List issues
         * @description Returns a paginated, lean list of issues. Use `GET /api/issues/{id}/` for the full detail view including comments, attachments, and activity.
         */
        get: operations["issues_list"];
        put?: never;
        post: operations["issues_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an issue
         * @description Returns the full issue, with `watchers`, `comments`, `attachments`, and `activity` embedded. The dedicated sub-resource endpoints remain available for paginated drill-down.
         */
        get: operations["issues_retrieve"];
        put: operations["issues_update"];
        post?: never;
        delete: operations["issues_destroy"];
        options?: never;
        head?: never;
        patch: operations["issues_partial_update"];
        trace?: never;
    };
    "/api/issues/{id}/activity/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List issue activity
         * @description Returns a list of all activity logs associated with the specified issue.
         */
        get: operations["issues_activity_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{id}/assignee/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Assign a user to an issue
         * @description Assigns the given user as the issue's assignee.
         */
        put: operations["issues_assignee_update"];
        post?: never;
        /**
         * Unassign the issue
         * @description Removes the current assignee from the issue.
         */
        delete: operations["issues_assignee_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{id}/attachments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List attachments for an issue
         * @description Returns all files attached to the given issue.
         */
        get: operations["issues_attachments_list"];
        put?: never;
        /**
         * Upload an attachment to an issue
         * @description Uploads a file as an attachment to the issue. Send as `multipart/form-data` with field `file`.
         */
        post: operations["issues_attachments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{id}/attachments/{attachment_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete an attachment
         * @description Deletes the attachment. Only the user who uploaded it can delete it.
         */
        delete: operations["issues_attachments_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{id}/comments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List comments for an issue
         * @description Returns a list of all comments associated with the specified issue.
         */
        get: operations["issues_comments_list"];
        put?: never;
        /**
         * Add a comment to an issue
         * @description Creates a new comment for the specified issue
         */
        post: operations["issues_comments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{id}/comments/{comment_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a comment
         * @description Deletes an existing comment. Only the creator of the comment can delete it.
         */
        delete: operations["issues_comments_destroy"];
        options?: never;
        head?: never;
        /**
         * Edit a comment
         * @description Updates an existing comment. Only the creator of the comment can edit it.
         */
        patch: operations["issues_comments_partial_update"];
        trace?: never;
    };
    "/api/issues/{id}/due-date/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Clear issue due date
         * @description Removes the deadline and the reason from the issue.
         */
        delete: operations["issues_due_date_destroy"];
        options?: never;
        head?: never;
        /**
         * Set or update issue due date
         * @description Sets or updates the deadline and/or the reason for a specific issue. At least one of `deadline` / `due_date_reason` must be provided.
         */
        patch: operations["issues_due_date_partial_update"];
        trace?: never;
    };
    "/api/issues/{id}/tags/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Attach a tag to an issue
         * @description Attaches a tag to the issue by `name` (case-insensitive). The tag is created with the given `color` if it does not already exist, mirroring the HTML form behavior.
         */
        post: operations["issues_tags_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{id}/tags/{tag_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Detach a tag from an issue
         * @description Removes the given tag from the issue. The tag itself is not deleted.
         */
        delete: operations["issues_tags_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{id}/watchers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a watcher to an issue
         * @description Adds the given user as a watcher of the issue. Returns 409 if the user is already watching.
         */
        post: operations["issues_watchers_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{id}/watchers/{user_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a watcher from an issue
         * @description Removes the given user from the issue's watchers. Returns 404 if the user is not watching.
         */
        delete: operations["issues_watchers_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{id}/watchers/toggle/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Toggle the current user's watch state
         * @description Toggles whether the requesting user is watching the issue. Response indicates the resulting state.
         */
        post: operations["issues_watchers_toggle_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/bulk/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk create issues
         * @description Creates multiple issues in a single request. Returns the list of created issues.
         */
        post: operations["issues_bulk_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the current user
         * @description Returns the authenticated user's profile with `assigned`, `watched`, and `comments` embedded.
         */
        get: operations["me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update the current user's profile
         * @description Partially updates the authenticated user's profile fields. Returns the updated profile (without embedded collections).
         */
        patch: operations["me_partial_update"];
        trace?: never;
    };
    "/api/me/avatar/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload the current user's avatar
         * @description Uploads a new avatar image. Send as `multipart/form-data` with field `avatar`.
         */
        post: operations["me_avatar_create"];
        /**
         * Remove the current user's avatar
         * @description Deletes the authenticated user's avatar file. No-op if no avatar is set.
         */
        delete: operations["me_avatar_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke the current user's API token
         * @description Deletes the authenticated user's API token.
         */
        delete: operations["me_token_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/token/rotate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the current user's API token
         * @description Generates a new API token for the authenticated user, invalidating any previous token.
         */
        post: operations["me_token_rotate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/due-dates/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the settings */
        get: operations["settings_due_dates_list"];
        put?: never;
        /**
         * Create a new due date
         * @description Defines a default time offset (days before/after) to automatically calculate deadlines.
         */
        post: operations["settings_due_dates_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/due-dates/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the setting */
        get: operations["settings_due_dates_retrieve"];
        /**
         * Update a due date
         * @description Updates all fields of an existing due date setting.
         */
        put: operations["settings_due_dates_update"];
        post?: never;
        /** Delete the setting */
        delete: operations["settings_due_dates_destroy"];
        options?: never;
        head?: never;
        /**
         * Partial update a due date
         * @description Adjust the name, the color, the offset days or the before/after calculation for a due date setting.
         */
        patch: operations["settings_due_dates_partial_update"];
        trace?: never;
    };
    "/api/settings/priorities/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the settings */
        get: operations["settings_priorities_list"];
        put?: never;
        /**
         * Create a new priority
         * @description Creates a new priority level (e.g., High, Low) to help organize the order of work.
         */
        post: operations["settings_priorities_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/priorities/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the setting */
        get: operations["settings_priorities_retrieve"];
        /**
         * Update a priority
         * @description Updates all fields of an existing priority.
         */
        put: operations["settings_priorities_update"];
        post?: never;
        /** Delete the setting */
        delete: operations["settings_priorities_destroy"];
        options?: never;
        head?: never;
        /**
         * Partial update a priority
         * @description Updates one or more fields of an existing priority.
         */
        patch: operations["settings_priorities_partial_update"];
        trace?: never;
    };
    "/api/settings/severities/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the settings */
        get: operations["settings_severities_list"];
        put?: never;
        /**
         * Create a new severity
         * @description Defines a new severity level (e.g., Critical, Normal, Minor) to classify how serious an issue is.
         */
        post: operations["settings_severities_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/severities/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the setting */
        get: operations["settings_severities_retrieve"];
        /**
         * Update a severity
         * @description Updates all fields of an existing severity.
         */
        put: operations["settings_severities_update"];
        post?: never;
        /** Delete the setting */
        delete: operations["settings_severities_destroy"];
        options?: never;
        head?: never;
        /**
         * Partial update a severity
         * @description Updates one or more fields of an existing severity.
         */
        patch: operations["settings_severities_partial_update"];
        trace?: never;
    };
    "/api/settings/statuses/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the settings */
        get: operations["settings_statuses_list"];
        put?: never;
        /**
         * Create a new status
         * @description Creates a new status for the workflow. Use 'isclosed' to mark if this status represents a finished task.
         */
        post: operations["settings_statuses_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/statuses/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the setting */
        get: operations["settings_statuses_retrieve"];
        /**
         * Update a status
         * @description Updates all fields of an existing status.
         */
        put: operations["settings_statuses_update"];
        post?: never;
        /** Delete the setting */
        delete: operations["settings_statuses_destroy"];
        options?: never;
        head?: never;
        /**
         * Partial update a status
         * @description Modify specific fields of a status like its color or closed state.
         */
        patch: operations["settings_statuses_partial_update"];
        trace?: never;
    };
    "/api/settings/tags/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the settings */
        get: operations["settings_tags_list"];
        put?: never;
        /**
         * Create a new tag
         * @description Adds a new tag that can be attached to issues for better categorization.
         */
        post: operations["settings_tags_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/tags/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the setting */
        get: operations["settings_tags_retrieve"];
        /**
         * Update a tag
         * @description Updates all fields of an existing tag.
         */
        put: operations["settings_tags_update"];
        post?: never;
        /** Delete the setting */
        delete: operations["settings_tags_destroy"];
        options?: never;
        head?: never;
        /**
         * Partial update a tag
         * @description Updates one or more fields of an existing tag.
         */
        patch: operations["settings_tags_partial_update"];
        trace?: never;
    };
    "/api/settings/types/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the settings */
        get: operations["settings_types_list"];
        put?: never;
        /**
         * Create a new type
         * @description Adds a new issue type to the system (e.g., Bug, Feature, Task).
         */
        post: operations["settings_types_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/types/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the setting */
        get: operations["settings_types_retrieve"];
        /**
         * Update a type
         * @description Updates all fields of an existing issue type.
         */
        put: operations["settings_types_update"];
        post?: never;
        /** Delete the setting */
        delete: operations["settings_types_destroy"];
        options?: never;
        head?: never;
        /**
         * Partial update a type
         * @description Updates one or more fields of an existing issue type.
         */
        patch: operations["settings_types_partial_update"];
        trace?: never;
    };
    "/api/users/{username}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a user's public profile
         * @description Returns the public profile of the user with the given username, with `assigned` (open issues assigned to them) and `comments` (comments they authored) embedded. Anonymous-readable; for the current user's dashboard (which also includes `watched`), use `GET /api/me/`.
         */
        get: operations["users_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActivityRead: {
            readonly id: number;
            issue: number;
            readonly user: components["schemas"]["UserMini"];
            action: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        AssigneeWriteRequest: {
            user_id?: number | null;
        };
        AttachmentRead: {
            readonly id: number;
            /** Format: uri */
            file: string;
            original_filename: string;
            /** Format: date-time */
            readonly created_at: string;
            issue: number;
            uploaded_by: number;
        };
        AttachmentWriteRequest: {
            /** Format: binary */
            file: string;
        };
        AvatarUploadRequest: {
            /** Format: binary */
            avatar: string;
        };
        BasicSettingWriteRequest: {
            name: string;
            color: string;
        };
        BulkIssueWriteRequest: {
            /** @description Un subject por línea. Cada línea crea una issue separada. */
            subjects: string;
            /** @description ID del tipo */
            type: number;
            /** @description ID de la severidad */
            severity: number;
            /** @description ID de la prioridad */
            priority: number;
            /** @description ID del estado */
            status: number;
        };
        CommentRead: {
            readonly id: number;
            issue: number;
            readonly creator: components["schemas"]["UserMini"];
            text: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        CommentWriteRequest: {
            text: string;
        };
        DueDate: {
            readonly id: number;
            name: string;
            color: string;
            /** Format: int64 */
            days?: number | null;
            isBefore?: boolean;
            creator?: number | null;
        };
        DueDateSettingWriteRequest: {
            name: string;
            color: string;
            days: number;
            /** @description Ex: "true" o "false" */
            isBefore: string;
        };
        IssueDetail: {
            readonly id: number;
            subject: string;
            description: string;
            readonly creator: components["schemas"]["UserMini"];
            readonly assigned_to: components["schemas"]["UserMini"];
            readonly type: string;
            readonly severity: string;
            readonly priority: string;
            readonly status: string;
            readonly tags: string;
            /** Format: date */
            deadline?: string | null;
            due_date_reason?: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly modified_at: string;
            readonly watchers: components["schemas"]["UserMini"][];
            readonly comments: components["schemas"]["CommentRead"][];
            readonly attachments: components["schemas"]["AttachmentRead"][];
            readonly activity: components["schemas"]["ActivityRead"][];
        };
        IssueRead: {
            readonly id: number;
            subject: string;
            description: string;
            readonly creator: components["schemas"]["UserMini"];
            readonly assigned_to: components["schemas"]["UserMini"];
            readonly type: string;
            readonly severity: string;
            readonly priority: string;
            readonly status: string;
            readonly tags: string;
            /** Format: date */
            deadline?: string | null;
            due_date_reason?: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly modified_at: string;
        };
        IssueWriteFormRequest: {
            subject: string;
            description?: string;
            /** @description ID del usuario asignado */
            assigned_to?: number | null;
            /** @description ID del tipo */
            type: number;
            /** @description ID de la severidad */
            severity: number;
            /** @description ID de la prioridad */
            priority: number;
            /** @description ID del estado */
            status: number;
            /**
             * Format: date
             * @description Formato: YYYY-MM-DD
             */
            deadline?: string | null;
        };
        MeDetail: {
            readonly id: number;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            first_name?: string;
            last_name?: string;
            bio?: string | null;
            /**
             * Profile picture
             * Format: uri
             */
            avatar?: string | null;
            readonly assigned: components["schemas"]["IssueRead"][];
            readonly comments: components["schemas"]["CommentRead"][];
            readonly watched: components["schemas"]["IssueRead"][];
        };
        PaginatedActivityReadList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ActivityRead"][];
        };
        PaginatedAttachmentReadList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["AttachmentRead"][];
        };
        PaginatedCommentReadList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["CommentRead"][];
        };
        PaginatedDueDateList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["DueDate"][];
        };
        PaginatedIssueReadList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["IssueRead"][];
        };
        PaginatedPriorityList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Priority"][];
        };
        PaginatedSeverityList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Severity"][];
        };
        PaginatedStatusList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Status"][];
        };
        PaginatedTagList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Tag"][];
        };
        PaginatedTypeList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Type"][];
        };
        PatchedBasicSettingWriteRequest: {
            name?: string;
            color?: string;
        };
        PatchedCommentWriteRequest: {
            text?: string;
        };
        PatchedDueDateSettingWriteRequest: {
            name?: string;
            color?: string;
            days?: number;
            /** @description Ex: "true" o "false" */
            isBefore?: string;
        };
        PatchedDueDateWriteRequest: {
            /** Format: date */
            deadline?: string | null;
            due_date_reason?: string | null;
        };
        PatchedIssueWriteFormRequest: {
            subject?: string;
            description?: string;
            /** @description ID del usuario asignado */
            assigned_to?: number | null;
            /** @description ID del tipo */
            type?: number;
            /** @description ID de la severidad */
            severity?: number;
            /** @description ID de la prioridad */
            priority?: number;
            /** @description ID del estado */
            status?: number;
            /**
             * Format: date
             * @description Formato: YYYY-MM-DD
             */
            deadline?: string | null;
        };
        PatchedStatusSettingWriteRequest: {
            name?: string;
            color?: string;
            slug?: string;
            /** @description Ex: "true" o "false" */
            isclosed?: string;
        };
        Priority: {
            readonly id: number;
            name: string;
            color: string;
            creator?: number | null;
        };
        SettingsWrite: {
            name: string;
            /** @description Hex color code: #RRGGBB where RR, GG, BB are two-digit hex numbers from 00 to FF */
            color: string;
        };
        Severity: {
            readonly id: number;
            name: string;
            color: string;
            creator?: number | null;
        };
        Status: {
            readonly id: number;
            name: string;
            color: string;
            slug: string;
            is_closed?: boolean;
            creator?: number | null;
        };
        StatusSettingWriteRequest: {
            name: string;
            color: string;
            slug: string;
            /** @description Ex: "true" o "false" */
            isclosed?: string;
        };
        StatusWrite: {
            name: string;
            /** @description Hex color code: #RRGGBB where RR, GG, BB are two-digit hex numbers from 00 to FF */
            color: string;
            slug: string;
            /** @default false */
            is_closed: boolean;
        };
        Tag: {
            readonly id: number;
            name: string;
            color: string;
            creator?: number | null;
        };
        TagAttachWriteRequest: {
            name: string;
            /**
             * @description Hex color #RRGGBB. Defaults to #6b7280 if omitted.
             * @default #6b7280
             */
            color: string;
        };
        TokenRotateResponse: {
            token: string;
        };
        Type: {
            readonly id: number;
            name: string;
            color: string;
            creator?: number | null;
        };
        UserDetail: {
            readonly id: number;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            first_name?: string;
            last_name?: string;
            bio?: string | null;
            /**
             * Profile picture
             * Format: uri
             */
            avatar?: string | null;
            readonly assigned: components["schemas"]["IssueRead"][];
            readonly comments: components["schemas"]["CommentRead"][];
        };
        UserMini: {
            readonly id: number;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            /**
             * Profile picture
             * Format: uri
             */
            avatar?: string | null;
        };
        UserRead: {
            readonly id: number;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            first_name?: string;
            last_name?: string;
            bio?: string | null;
            /**
             * Profile picture
             * Format: uri
             */
            avatar?: string | null;
        };
        WatcherToggleResponse: {
            watching: boolean;
        };
        WatcherWriteRequest: {
            user_id: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    issues_list: {
        parameters: {
            query?: {
                /** @description Ordenación, ej: -created_at, status, priority */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Filtra por ID de priority */
                priority?: number;
                /** @description Busca por subject o descripción */
                search?: string;
                /** @description Filtra por ID de status */
                status?: number;
                /** @description Filtra por ID de type */
                type?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedIssueReadList"];
                };
            };
        };
    };
    issues_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueWriteFormRequest"];
                "multipart/form-data": components["schemas"]["IssueWriteFormRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["IssueWriteFormRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueRead"];
                };
            };
        };
    };
    issues_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this issue. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDetail"];
                };
            };
        };
    };
    issues_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this issue. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    issues_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this issue. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    issues_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this issue. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedIssueWriteFormRequest"];
                "multipart/form-data": components["schemas"]["PatchedIssueWriteFormRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedIssueWriteFormRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueRead"];
                };
            };
        };
    };
    issues_activity_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this issue. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedActivityReadList"];
                };
            };
            /** @description No response body */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    issues_assignee_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this issue. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AssigneeWriteRequest"];
                "multipart/form-data": components["schemas"]["AssigneeWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AssigneeWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueRead"];
                };
            };
            /** @description No response body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    issues_assignee_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this issue. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    issues_attachments_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this issue. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAttachmentReadList"];
                };
            };
            /** @description No response body */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    issues_attachments_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this issue. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["AttachmentWriteRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentRead"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description No response body */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    issues_attachments_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the attachment to delete. */
                attachment_id: number;
                /** @description A unique integer value identifying this issue. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    issues_comments_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this issue. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCommentReadList"];
                };
            };
            /** @description No response body */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    issues_comments_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this issue. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentWriteRequest"];
                "multipart/form-data": components["schemas"]["CommentWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CommentWriteRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentRead"];
                };
            };
            /** @description No response body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    issues_comments_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comment_id: number;
                /** @description A unique integer value identifying this issue. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    issues_comments_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comment_id: number;
                /** @description A unique integer value identifying this issue. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCommentWriteRequest"];
                "multipart/form-data": components["schemas"]["PatchedCommentWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCommentWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentRead"];
                };
            };
            /** @description No response body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    issues_due_date_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this issue. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    issues_due_date_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this issue. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedDueDateWriteRequest"];
                "multipart/form-data": components["schemas"]["PatchedDueDateWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedDueDateWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueRead"];
                };
            };
            /** @description No response body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    issues_tags_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this issue. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagAttachWriteRequest"];
                "multipart/form-data": components["schemas"]["TagAttachWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TagAttachWriteRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueRead"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description No response body */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    issues_tags_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this issue. */
                id: number;
                /** @description ID of the tag to detach. */
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    issues_watchers_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this issue. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatcherWriteRequest"];
                "multipart/form-data": components["schemas"]["WatcherWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["WatcherWriteRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueRead"];
                };
            };
            /** @description No response body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    issues_watchers_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this issue. */
                id: number;
                /** @description ID of the user to remove from watchers. */
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    issues_watchers_toggle_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this issue. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatcherToggleResponse"];
                };
            };
            /** @description No response body */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    issues_bulk_create: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkIssueWriteRequest"];
                "multipart/form-data": components["schemas"]["BulkIssueWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["BulkIssueWriteRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedIssueReadList"];
                };
            };
            /** @description No response body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDetail"];
                };
            };
            /** @description No response body */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description No response body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_avatar_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["AvatarUploadRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description No response body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_avatar_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_token_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_token_rotate_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRotateResponse"];
                };
            };
            /** @description No response body */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    settings_due_dates_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDueDateList"];
                };
            };
        };
    };
    settings_due_dates_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DueDateSettingWriteRequest"];
                "multipart/form-data": components["schemas"]["DueDateSettingWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["DueDateSettingWriteRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsWrite"];
                };
            };
        };
    };
    settings_due_dates_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this due date. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DueDate"];
                };
            };
        };
    };
    settings_due_dates_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this due date. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DueDateSettingWriteRequest"];
                "multipart/form-data": components["schemas"]["DueDateSettingWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["DueDateSettingWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsWrite"];
                };
            };
        };
    };
    settings_due_dates_destroy: {
        parameters: {
            query?: {
                /** @description ID of the setting that will replace the deleted one. */
                replacement?: number;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this due date. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    settings_due_dates_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this due date. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedDueDateSettingWriteRequest"];
                "multipart/form-data": components["schemas"]["PatchedDueDateSettingWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedDueDateSettingWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsWrite"];
                };
            };
        };
    };
    settings_priorities_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPriorityList"];
                };
            };
        };
    };
    settings_priorities_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BasicSettingWriteRequest"];
                "multipart/form-data": components["schemas"]["BasicSettingWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["BasicSettingWriteRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsWrite"];
                };
            };
        };
    };
    settings_priorities_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this priority. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Priority"];
                };
            };
        };
    };
    settings_priorities_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this priority. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BasicSettingWriteRequest"];
                "multipart/form-data": components["schemas"]["BasicSettingWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["BasicSettingWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsWrite"];
                };
            };
        };
    };
    settings_priorities_destroy: {
        parameters: {
            query?: {
                /** @description ID of the setting that will replace the deleted one. */
                replacement?: number;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this priority. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    settings_priorities_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this priority. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedBasicSettingWriteRequest"];
                "multipart/form-data": components["schemas"]["PatchedBasicSettingWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedBasicSettingWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsWrite"];
                };
            };
        };
    };
    settings_severities_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSeverityList"];
                };
            };
        };
    };
    settings_severities_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BasicSettingWriteRequest"];
                "multipart/form-data": components["schemas"]["BasicSettingWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["BasicSettingWriteRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsWrite"];
                };
            };
        };
    };
    settings_severities_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this severity. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Severity"];
                };
            };
        };
    };
    settings_severities_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this severity. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BasicSettingWriteRequest"];
                "multipart/form-data": components["schemas"]["BasicSettingWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["BasicSettingWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsWrite"];
                };
            };
        };
    };
    settings_severities_destroy: {
        parameters: {
            query?: {
                /** @description ID of the setting that will replace the deleted one. */
                replacement?: number;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this severity. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    settings_severities_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this severity. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedBasicSettingWriteRequest"];
                "multipart/form-data": components["schemas"]["PatchedBasicSettingWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedBasicSettingWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsWrite"];
                };
            };
        };
    };
    settings_statuses_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedStatusList"];
                };
            };
        };
    };
    settings_statuses_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusSettingWriteRequest"];
                "multipart/form-data": components["schemas"]["StatusSettingWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["StatusSettingWriteRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusWrite"];
                };
            };
        };
    };
    settings_statuses_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this status. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    settings_statuses_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this status. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusSettingWriteRequest"];
                "multipart/form-data": components["schemas"]["StatusSettingWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["StatusSettingWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusWrite"];
                };
            };
        };
    };
    settings_statuses_destroy: {
        parameters: {
            query?: {
                /** @description ID of the setting that will replace the deleted one. */
                replacement?: number;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this status. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    settings_statuses_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this status. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedStatusSettingWriteRequest"];
                "multipart/form-data": components["schemas"]["PatchedStatusSettingWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedStatusSettingWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusWrite"];
                };
            };
        };
    };
    settings_tags_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTagList"];
                };
            };
        };
    };
    settings_tags_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BasicSettingWriteRequest"];
                "multipart/form-data": components["schemas"]["BasicSettingWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["BasicSettingWriteRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsWrite"];
                };
            };
        };
    };
    settings_tags_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this tag. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
        };
    };
    settings_tags_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this tag. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BasicSettingWriteRequest"];
                "multipart/form-data": components["schemas"]["BasicSettingWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["BasicSettingWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsWrite"];
                };
            };
        };
    };
    settings_tags_destroy: {
        parameters: {
            query?: {
                /** @description ID of the setting that will replace the deleted one. */
                replacement?: number;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this tag. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    settings_tags_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this tag. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedBasicSettingWriteRequest"];
                "multipart/form-data": components["schemas"]["PatchedBasicSettingWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedBasicSettingWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsWrite"];
                };
            };
        };
    };
    settings_types_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTypeList"];
                };
            };
        };
    };
    settings_types_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BasicSettingWriteRequest"];
                "multipart/form-data": components["schemas"]["BasicSettingWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["BasicSettingWriteRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsWrite"];
                };
            };
        };
    };
    settings_types_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this type. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Type"];
                };
            };
        };
    };
    settings_types_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this type. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BasicSettingWriteRequest"];
                "multipart/form-data": components["schemas"]["BasicSettingWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["BasicSettingWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsWrite"];
                };
            };
        };
    };
    settings_types_destroy: {
        parameters: {
            query?: {
                /** @description ID of the setting that will replace the deleted one. */
                replacement?: number;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this type. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    settings_types_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this type. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedBasicSettingWriteRequest"];
                "multipart/form-data": components["schemas"]["PatchedBasicSettingWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedBasicSettingWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsWrite"];
                };
            };
        };
    };
    users_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Username of the target user. */
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetail"];
                };
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
